#!/bin/sh
# Upload file: settings.js
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_settings_js_content }}" \
  "{{ upload_settings_js_destination }}" \
  "settings.js" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_settings_js_uploaded"
