#!/bin/sh
# Configure native SSL for OCI LXC Deployer.
#
# Creates an on_start.d drop-in script that checks for SSL addon certificates
# and links them to the deployer's /secure/ directory where webapp.mts
# can pick them up via DEPLOYER_SSL_CERT / DEPLOYER_SSL_KEY env vars.
#
# Only active in native SSL mode. In proxy mode, nginx handles HTTPS.
#
# Requires:
#   - addon_ssl_mode: "proxy" or "native"
#
# Output: errors to stderr only

SSL_MODE="{{ addon_ssl_mode }}"

SCRIPT_PATH="/etc/lxc-oci-deployer/on_start.d/native-ssl.sh"

# Only configure for native mode
if [ "$SSL_MODE" != "native" ]; then
  echo "SSL mode is '$SSL_MODE', skipping native SSL configuration" >&2
  exit 0
fi

# Part 1: Write header with baked-in values
cat > "$SCRIPT_PATH" <<EOF
#!/bin/sh
# Native SSL - link addon certs to deployer secure volume
# Generated by oci-lxc-deployer
# Runs on every container start via the on_start_container dispatcher.
EOF

# Part 2: Append script body (no variable expansion)
cat >> "$SCRIPT_PATH" << 'NATIVESSLEOF'

ADDON_CERT="/etc/ssl/addon/server.crt"
ADDON_KEY="/etc/ssl/addon/server.key"
SECURE_DIR="/secure"

# Check if addon certs exist
if [ ! -f "$ADDON_CERT" ] || [ ! -f "$ADDON_KEY" ]; then
  echo "No SSL addon certificates found, skipping native SSL setup" >&2
  exit 0
fi

# Link/copy certs to secure directory
mkdir -p "$SECURE_DIR"

# Use symlinks to avoid duplication
ln -sf "$ADDON_CERT" "${SECURE_DIR}/server.crt"
ln -sf "$ADDON_KEY" "${SECURE_DIR}/server.key"

# Set environment variables for the deployer process
# These are picked up by webapp.mts on startup
ENV_FILE="/etc/lxc-oci-deployer/env"
mkdir -p "$(dirname "$ENV_FILE")"

# Only set if not already configured
if ! grep -q "DEPLOYER_SSL_CERT" "$ENV_FILE" 2>/dev/null; then
  echo "DEPLOYER_SSL_CERT=${SECURE_DIR}/server.crt" >> "$ENV_FILE"
  echo "DEPLOYER_SSL_KEY=${SECURE_DIR}/server.key" >> "$ENV_FILE"
  echo "DEPLOYER_SSL_GENERATE=false" >> "$ENV_FILE"
fi

echo "Native SSL configured: certs linked to ${SECURE_DIR}" >&2
NATIVESSLEOF

chmod 700 "$SCRIPT_PATH"
echo "Installed native SSL on-start script: ${SCRIPT_PATH}" >&2

# Run immediately for initial installation
echo "Running initial native SSL setup..." >&2
"$SCRIPT_PATH"
