listener 8883
cafile /mosquitto/config/certs/chain.pem
certfile /mosquitto/config/certs/cert.pem
keyfile /mosquitto/config/certs/privkey.pem
require_certificate true
use_identity_as_username true
allow_anonymous false
