services:
  zitadel:
    image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION:-latest}
    restart: unless-stopped
    command: 'start-from-init --masterkey "{{ ZITADEL_MASTERKEY }}" --tlsMode ${ZITADEL_TLS_MODE:-disabled}'
    environment:
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_EXTERNALDOMAIN:-localhost}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE:-false}
      ZITADEL_EXTERNALPORT: ${ZITADEL_PORT:-8080}
      ZITADEL_TLS_CERTPATH: /certs/fullchain.pem
      ZITADEL_TLS_KEYPATH: /certs/privkey.pem
      ZITADEL_DATABASE_POSTGRES_HOST: {{ POSTGRES_HOST }}
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${ZITADEL_DB:-zitadel}
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${POSTGRES_USER:-postgres}
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${POSTGRES_USER:-postgres}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: admin
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: Password1!
    volumes:
      - /certs:/certs:ro
    ports:
      - "${ZITADEL_PORT:-8080}:8080"
