#!/bin/sh
# Install the ACME certificate renewal on-start drop-in script.
#
# Creates /etc/lxc-oci-deployer/on_start.d/acme-renew.sh which handles:
# - Installing acme.sh if not present
# - Issuing/renewing certificates via Cloudflare DNS challenge
# - Running a background loop for periodic renewal (every 24h)
# - Calling /etc/lxc-oci-deployer/reload_certificates after renewal
#
# Requires:
#   - CF_TOKEN: Cloudflare API token
#   - acme_domain: Domain for the certificate
#   - acme_email: (optional) Email for LE registration
#   - acme.cert_dir: Certificate directory in container
#   - acme.needs_server_cert: Whether to issue server cert
#   - acme.needs_ca_cert: Whether to write CA/intermediate cert
#   - alpine_mirror: (optional) Alpine mirror URL
#   - debian_mirror: (optional) Debian mirror URL
#
# Output: errors to stderr only

CF_API_TOKEN="{{ CF_TOKEN }}"
ACME_DOMAIN="{{ acme_domain }}"
ACME_EMAIL="{{ acme_email }}"
CERT_DIR="{{ acme.cert_dir }}"
NEEDS_SERVER_CERT="{{ acme.needs_server_cert }}"
NEEDS_CA_CERT="{{ acme.needs_ca_cert }}"
ALPINE_MIRROR="{{ alpine_mirror }}"
DEBIAN_MIRROR="{{ debian_mirror }}"

SCRIPT_PATH="/etc/lxc-oci-deployer/on_start.d/acme-renew.sh"
mkdir -p "$(dirname "$SCRIPT_PATH")"

# Part 1: Write header with baked-in values (expanded from template)
cat > "$SCRIPT_PATH" <<EOF
#!/bin/sh
# ACME certificate renewal - issue, renew, and maintain
# Generated by oci-lxc-deployer
# Runs on every container start via the on_start_container dispatcher.

CF_API_TOKEN="$CF_API_TOKEN"
ACME_DOMAIN="$ACME_DOMAIN"
ACME_EMAIL="$ACME_EMAIL"
CERT_DIR="$CERT_DIR"
NEEDS_SERVER_CERT="$NEEDS_SERVER_CERT"
NEEDS_CA_CERT="$NEEDS_CA_CERT"
ALPINE_MIRROR="$ALPINE_MIRROR"
DEBIAN_MIRROR="$DEBIAN_MIRROR"
EOF

# Part 2: Append script body (no variable expansion)
cat >> "$SCRIPT_PATH" << 'ACMEEOF'

APP_UID="${1:-0}"
APP_GID="${2:-0}"
ACME_HOME="/root/.acme.sh"
RELOAD_SCRIPT="/etc/lxc-oci-deployer/reload_certificates"

# --- Check if renewal loop already running ---
if pgrep -f "acme-renew-loop" >/dev/null 2>&1; then
  echo "ACME renewal loop already running" >&2
  exit 0
fi

# --- Detect OS ---
OS_TYPE=""
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_TYPE="$ID"
elif command -v apk >/dev/null 2>&1; then
  OS_TYPE="alpine"
elif command -v apt-get >/dev/null 2>&1; then
  OS_TYPE="debian"
fi

# --- Install curl and openssl if not present ---
if ! command -v curl >/dev/null 2>&1 || ! command -v openssl >/dev/null 2>&1; then
  echo "Installing curl and openssl..." >&2
  case "$OS_TYPE" in
    alpine)
      if [ -n "$ALPINE_MIRROR" ]; then
        ALPINE_VERSION=$(cut -d. -f1,2 < /etc/alpine-release 2>/dev/null)
        if [ -n "$ALPINE_VERSION" ]; then
          cat > /etc/apk/repositories <<MIRROREOF
${ALPINE_MIRROR}/v${ALPINE_VERSION}/main
${ALPINE_MIRROR}/v${ALPINE_VERSION}/community
MIRROREOF
          echo "Set Alpine mirror: $ALPINE_MIRROR" >&2
        fi
      fi
      apk update >&2
      apk add --no-cache curl openssl >&2
      ;;
    debian|ubuntu)
      if [ -n "$DEBIAN_MIRROR" ]; then
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          CODENAME="$VERSION_CODENAME"
        fi
        if [ -z "$CODENAME" ]; then
          CODENAME="stable"
        fi
        cat > /etc/apt/sources.list <<MIRROREOF
deb ${DEBIAN_MIRROR} ${CODENAME} main
deb ${DEBIAN_MIRROR} ${CODENAME}-updates main
MIRROREOF
        echo "Set Debian mirror: $DEBIAN_MIRROR" >&2
      fi
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -qq >&2
      apt-get install -y --no-install-recommends curl openssl >&2
      ;;
  esac
fi

# --- Install acme.sh if not present ---
if [ ! -f "$ACME_HOME/acme.sh" ]; then
  echo "Installing acme.sh..." >&2
  if [ -n "$ACME_EMAIL" ]; then
    curl -s https://get.acme.sh | sh -s email="$ACME_EMAIL" >&2
  else
    curl -s https://get.acme.sh | sh >&2
  fi
  if [ ! -f "$ACME_HOME/acme.sh" ]; then
    echo "ERROR: Failed to install acme.sh" >&2
    exit 1
  fi
  echo "acme.sh installed successfully" >&2
fi

# --- Function: issue or renew certificate ---
acme_issue_or_renew() {
  export CF_Token="$CF_API_TOKEN"

  ACME_ARGS="--dns dns_cf -d $ACME_DOMAIN"

  # Build install command args based on needs_server_cert / needs_ca_cert
  INSTALL_ARGS=""
  if [ "$NEEDS_SERVER_CERT" = "true" ]; then
    INSTALL_ARGS="$INSTALL_ARGS --key-file ${CERT_DIR}/privkey.pem"
    INSTALL_ARGS="$INSTALL_ARGS --cert-file ${CERT_DIR}/cert.pem"
    INSTALL_ARGS="$INSTALL_ARGS --fullchain-file ${CERT_DIR}/fullchain.pem"
  fi
  if [ "$NEEDS_CA_CERT" = "true" ]; then
    INSTALL_ARGS="$INSTALL_ARGS --ca-file ${CERT_DIR}/chain.pem"
  fi

  if [ -z "$INSTALL_ARGS" ]; then
    echo "WARNING: Neither server cert nor CA cert requested, nothing to do" >&2
    return 0
  fi

  # Issue certificate if not yet issued for this domain
  if ! "$ACME_HOME/acme.sh" --list | grep -q "$ACME_DOMAIN"; then
    echo "Issuing certificate for $ACME_DOMAIN..." >&2
    "$ACME_HOME/acme.sh" --issue $ACME_ARGS >&2
    ISSUE_RC=$?
    if [ $ISSUE_RC -ne 0 ] && [ $ISSUE_RC -ne 2 ]; then
      echo "ERROR: Failed to issue certificate (exit code: $ISSUE_RC)" >&2
      return 1
    fi
  else
    echo "Certificate for $ACME_DOMAIN already issued, attempting renewal..." >&2
    "$ACME_HOME/acme.sh" --renew -d "$ACME_DOMAIN" >&2 || true
  fi

  # Install certificate files to target directory
  mkdir -p "$CERT_DIR"
  echo "Installing certificate files to $CERT_DIR..." >&2
  "$ACME_HOME/acme.sh" --install-cert -d "$ACME_DOMAIN" $INSTALL_ARGS >&2
  if [ $? -ne 0 ]; then
    echo "ERROR: Failed to install certificate files" >&2
    return 1
  fi

  # Set ownership
  if [ "$APP_UID" != "0" ] || [ "$APP_GID" != "0" ]; then
    chown -R "${APP_UID}:${APP_GID}" "$CERT_DIR" 2>/dev/null || true
  fi

  echo "Certificate files installed successfully" >&2
  return 0
}

# --- Initial certificate issuance (synchronous) ---
acme_issue_or_renew

# --- Start background renewal loop ---
(
  # Tag the process for pgrep detection
  exec -a acme-renew-loop sh -c '
    while true; do
      sleep 86400
      echo "[acme-renew-loop] Checking certificate renewal..." >&2
      "'"$ACME_HOME"'/acme.sh" --renew -d "'"$ACME_DOMAIN"'" >&2 || true

      # Reinstall cert files
      INSTALL_ARGS=""
      if [ "'"$NEEDS_SERVER_CERT"'" = "true" ]; then
        INSTALL_ARGS="$INSTALL_ARGS --key-file '"${CERT_DIR}"'/privkey.pem"
        INSTALL_ARGS="$INSTALL_ARGS --cert-file '"${CERT_DIR}"'/cert.pem"
        INSTALL_ARGS="$INSTALL_ARGS --fullchain-file '"${CERT_DIR}"'/fullchain.pem"
      fi
      if [ "'"$NEEDS_CA_CERT"'" = "true" ]; then
        INSTALL_ARGS="$INSTALL_ARGS --ca-file '"${CERT_DIR}"'/chain.pem"
      fi
      if [ -n "$INSTALL_ARGS" ]; then
        "'"$ACME_HOME"'/acme.sh" --install-cert -d "'"$ACME_DOMAIN"'" $INSTALL_ARGS >&2 || true
      fi

      # Set ownership
      if [ "'"$APP_UID"'" != "0" ] || [ "'"$APP_GID"'" != "0" ]; then
        chown -R "'"${APP_UID}:${APP_GID}"'" "'"$CERT_DIR"'" 2>/dev/null || true
      fi

      # Trigger reload hook if present
      if [ -x "'"$RELOAD_SCRIPT"'" ]; then
        echo "[acme-renew-loop] Running reload_certificates hook..." >&2
        "'"$RELOAD_SCRIPT"'" >&2 || true
      fi
    done
  '
) &

echo "ACME renewal loop started in background (PID: $!)" >&2
ACMEEOF

chmod 700 "$SCRIPT_PATH"
echo "Installed ACME renewal on-start script: ${SCRIPT_PATH}" >&2

# Run immediately for initial installation
echo "Running initial ACME certificate setup..." >&2
"$SCRIPT_PATH"
