#!/bin/sh
# Install the SSL proxy on-start drop-in script.
#
# Creates /etc/lxc-oci-deployer/on_start.d/ssl-proxy.sh which handles:
# - Docker-Compose detection (skip if compose app — handled by 325)
# - nginx installation and SSL configuration (proxy mode)
# - iptables rules to block external HTTP access (proxy mode)
# - Native/certs mode: exit (app handles HTTPS itself or only certs needed)
#
# Requires:
#   - ssl.mode: "proxy", "native", or "certs"
#   - http_port: Application HTTP port
#   - https_port: HTTPS port for nginx proxy
#   - alpine_mirror: (optional) Alpine mirror URL
#   - debian_mirror: (optional) Debian mirror URL
#
# Output: errors to stderr only

SSL_MODE="{{ ssl.mode }}"
HTTP_PORT="{{ http_port }}"
HTTPS_PORT="{{ https_port }}"
ALPINE_MIRROR="{{ alpine_mirror }}"
DEBIAN_MIRROR="{{ debian_mirror }}"

SCRIPT_PATH="/etc/lxc-oci-deployer/on_start.d/ssl-proxy.sh"
mkdir -p "$(dirname "$SCRIPT_PATH")"

# Part 1: Write header with baked-in values (expanded from template)
cat > "$SCRIPT_PATH" <<EOF
#!/bin/sh
# SSL proxy - install, configure and start
# Generated by oci-lxc-deployer
# Runs on every container start via the on_start_container dispatcher.

SSL_MODE="$SSL_MODE"
HTTP_PORT="$HTTP_PORT"
HTTPS_PORT="$HTTPS_PORT"
ALPINE_MIRROR="$ALPINE_MIRROR"
DEBIAN_MIRROR="$DEBIAN_MIRROR"
EOF

# Part 2: Append script body (no variable expansion)
cat >> "$SCRIPT_PATH" << 'SSLEOF'

CERT_DIR="/etc/ssl/addon"
NGINX_CONF_DIR=""

# --- Native mode: nothing to do ---
if [ "$SSL_MODE" = "native" ]; then
  echo "SSL native mode: app handles HTTPS itself" >&2
  exit 0
fi

# --- Certs mode: nothing to do ---
if [ "$SSL_MODE" = "certs" ]; then
  echo "SSL certs mode: certificates only, no proxy needed" >&2
  exit 0
fi

# --- Docker-Compose detection ---
# If this is a compose app, the nginx injection (325) handles everything.
# We only need to ensure compose services are running.
if [ -d /opt/docker-compose ]; then
  COMPOSE_DIR=$(find /opt/docker-compose -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)
  if [ -n "$COMPOSE_DIR" ]; then
    echo "Docker-Compose app detected, ensuring services are running..." >&2
    cd "$COMPOSE_DIR" || exit 0
    docker compose up -d >&2 2>&1 || true
    exit 0
  fi
fi

# --- Check if certificates exist ---
if [ ! -f "${CERT_DIR}/fullchain.pem" ] || [ ! -f "${CERT_DIR}/privkey.pem" ]; then
  echo "Warning: SSL certificates not found in ${CERT_DIR}, skipping proxy setup" >&2
  exit 0
fi

# --- Check if nginx is already running ---
if pgrep -x nginx >/dev/null 2>&1; then
  echo "nginx already running" >&2
  exit 0
fi

# --- Detect OS ---
OS_TYPE=""
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_TYPE="$ID"
elif command -v apk >/dev/null 2>&1; then
  OS_TYPE="alpine"
elif command -v apt-get >/dev/null 2>&1; then
  OS_TYPE="debian"
fi

# --- Install nginx and iptables if not present ---
if ! command -v nginx >/dev/null 2>&1 || ! command -v iptables >/dev/null 2>&1; then
  echo "Installing nginx and iptables..." >&2

  case "$OS_TYPE" in
    alpine)
      if [ -n "$ALPINE_MIRROR" ]; then
        ALPINE_VERSION=$(cut -d. -f1,2 < /etc/alpine-release 2>/dev/null)
        if [ -n "$ALPINE_VERSION" ]; then
          cat > /etc/apk/repositories <<MIRROREOF
${ALPINE_MIRROR}/v${ALPINE_VERSION}/main
${ALPINE_MIRROR}/v${ALPINE_VERSION}/community
MIRROREOF
          echo "Set Alpine mirror: $ALPINE_MIRROR" >&2
        fi
      fi
      apk update >&2
      apk add --no-cache nginx iptables >&2
      ;;
    debian|ubuntu)
      if [ -n "$DEBIAN_MIRROR" ]; then
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          CODENAME="$VERSION_CODENAME"
        fi
        if [ -z "$CODENAME" ]; then
          CODENAME="stable"
        fi
        cat > /etc/apt/sources.list <<MIRROREOF
deb ${DEBIAN_MIRROR} ${CODENAME} main
deb ${DEBIAN_MIRROR} ${CODENAME}-updates main
MIRROREOF
        echo "Set Debian mirror: $DEBIAN_MIRROR" >&2
      fi
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -qq >&2
      apt-get install -y --no-install-recommends nginx iptables >&2
      ;;
  esac
fi

# --- Determine nginx config directory ---
if [ -d /etc/nginx/http.d ]; then
  # Alpine
  NGINX_CONF_DIR="/etc/nginx/http.d"
  # Remove default site
  rm -f /etc/nginx/http.d/default.conf 2>/dev/null
elif [ -d /etc/nginx/sites-enabled ]; then
  # Debian/Ubuntu
  NGINX_CONF_DIR="/etc/nginx/conf.d"
  rm -f /etc/nginx/sites-enabled/default 2>/dev/null
  mkdir -p /etc/nginx/conf.d
elif [ -d /etc/nginx/conf.d ]; then
  NGINX_CONF_DIR="/etc/nginx/conf.d"
else
  # Fallback
  NGINX_CONF_DIR="/etc/nginx/conf.d"
  mkdir -p "$NGINX_CONF_DIR"
fi

# --- Write nginx SSL config ---
cat > "${NGINX_CONF_DIR}/ssl-proxy.conf" <<NGINXEOF
server {
    listen ${HTTPS_PORT} ssl;
    server_name _;

    ssl_certificate ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:${HTTP_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 86400;
    }
}
NGINXEOF

echo "Wrote nginx SSL config to ${NGINX_CONF_DIR}/ssl-proxy.conf" >&2

# --- Set iptables rules to block external HTTP access ---
# Allow localhost to access HTTP port (nginx -> app)
iptables -C INPUT -i lo -p tcp --dport "${HTTP_PORT}" -j ACCEPT 2>/dev/null || \
  iptables -I INPUT -i lo -p tcp --dport "${HTTP_PORT}" -j ACCEPT

# Block external access to HTTP port
iptables -C INPUT -p tcp --dport "${HTTP_PORT}" -j DROP 2>/dev/null || \
  iptables -A INPUT -p tcp --dport "${HTTP_PORT}" -j DROP

echo "iptables: blocked external access to HTTP port ${HTTP_PORT}" >&2

# --- Start nginx ---
echo "Starting nginx..." >&2
nginx >&2

echo "SSL proxy setup complete (HTTPS on port ${HTTPS_PORT})" >&2
SSLEOF

chmod 700 "$SCRIPT_PATH"
echo "Installed SSL proxy on-start script: ${SCRIPT_PATH}" >&2

# Run immediately for initial installation
echo "Running initial SSL proxy setup..." >&2
"$SCRIPT_PATH"
