#!/bin/sh
# Write a dockerd on-start drop-in script for docker-compose applications.
#
# The docker-compose base image ships docker.io but no init system, so dockerd
# must be launched explicitly on every container start. The post_start template
# 307-post-start-dockerd.json only runs during installation/reconfigure; this
# script ensures dockerd is also started after a plain `pct restart` by placing
# a drop-in script in /etc/proxvex/on_start.d/.
#
# Runs on the PVE host (execute_on: ve). The generated script is invoked inside
# the container by the on_start_container dispatcher (written by
# 166-conf-write-on-start-scripts.json or by this script if needed).
#
# Inputs (template variables):
#   hostname              - Container hostname
#   vm_id                 - Container VMID
#   docker_registry_mirror - Optional Docker Hub mirror URL
#   ghcr_registry_mirror  - Optional ghcr.io mirror URL
#
# Output: JSON to stdout

set -eu

HOSTNAME="{{ hostname }}"
VM_ID="{{ vm_id }}"
DOCKER_REGISTRY_MIRROR="{{ docker_registry_mirror }}"
GHCR_REGISTRY_MIRROR="{{ ghcr_registry_mirror }}"

log() { echo "$@" >&2; }

# Normalize NOT_DEFINED sentinels to empty strings.
[ "$DOCKER_REGISTRY_MIRROR" = "NOT_DEFINED" ] && DOCKER_REGISTRY_MIRROR=""
[ "$GHCR_REGISTRY_MIRROR" = "NOT_DEFINED" ] && GHCR_REGISTRY_MIRROR=""

# For reconfigure: volumes keep the previous container's hostname, but
# {{ hostname }} carries the scenario's intended new hostname. Look up the
# actual container hostname via pct config so the volume lookup matches.
ACTUAL_HOST=""
if [ -n "$VM_ID" ] && [ "$VM_ID" != "NOT_DEFINED" ]; then
  ACTUAL_HOST=$(pct config "$VM_ID" 2>/dev/null | awk '/^hostname:/ {print $2; exit}' || true)
fi
[ -z "$ACTUAL_HOST" ] && ACTUAL_HOST="$HOSTNAME"

SAFE_HOST=$(pve_sanitize_name "$ACTUAL_HOST")
# Tolerant lookup: a container without the proxvex volume (e.g. one created
# before the volume became standard for docker-compose apps) has nowhere to
# put the hook. That is a skip, not an installation failure — so the lookup
# must not abort the script under `set -e`.
VOLUME_DIR=$(resolve_host_volume "$SAFE_HOST" "proxvex" "$VM_ID" 2>/dev/null || echo "")

if [ -z "$VOLUME_DIR" ] || [ ! -d "$VOLUME_DIR" ]; then
  log "Warning: no proxvex volume for ${SAFE_HOST} (vmid ${VM_ID}), skipping"
  printf '[{"id":"dockerd_on_start_written","value":"false"}]\n'
  exit 0
fi

VOL_OWNER=$(stat -c '%u:%g' "$VOLUME_DIR" 2>/dev/null || echo "0:0")

mkdir -p "${VOLUME_DIR}/on_start.d"
chown "$VOL_OWNER" "${VOLUME_DIR}/on_start.d" 2>/dev/null || true

SCRIPT_PATH="${VOLUME_DIR}/on_start.d/50-start-dockerd.sh"

# Part 1: Write header with baked-in values (expanded from template).
cat > "$SCRIPT_PATH" <<EOF
#!/bin/sh
# Start dockerd in the background on container boot.
# Generated by proxvex (host-side pre_start).
# Runs on every container start via the on_start_container dispatcher.
#
# Idempotent: a second run notices dockerd already on its socket and exits 0.

DOCKER_REGISTRY_MIRROR="${DOCKER_REGISTRY_MIRROR}"
GHCR_REGISTRY_MIRROR="${GHCR_REGISTRY_MIRROR}"
[ "\$DOCKER_REGISTRY_MIRROR" = "NOT_DEFINED" ] && DOCKER_REGISTRY_MIRROR=""
[ "\$GHCR_REGISTRY_MIRROR" = "NOT_DEFINED" ] && GHCR_REGISTRY_MIRROR=""
EOF

# Part 2: Append script body (no variable expansion).
cat >> "$SCRIPT_PATH" << 'DOCKEREOF'

LOG_FILE="/var/log/dockerd.log"

if docker info >/dev/null 2>&1; then
  echo "dockerd already responsive — skipping start" >&2
  exit 0
fi

if [ ! -x /usr/sbin/dockerd ]; then
  echo "Error: /usr/sbin/dockerd missing — base image is broken" >&2
  exit 1
fi

# Clean up stale runtime state from a cloned or restored rootfs.
rm -f /var/run/docker.pid /var/run/docker.sock
rm -f /run/docker/containerd/containerd.pid \
      /run/docker/containerd/containerd.sock \
      /run/docker/containerd/containerd.sock.ttrpc \
      /run/docker/containerd/containerd-debug.sock

# Build daemon.json with explicit DNS upstreams and optional registry mirrors.
DNS_LIST=""
if [ -r /etc/resolv.conf ]; then
  for ns in $(awk '/^nameserver / {print $2}' /etc/resolv.conf); do
    case "$ns" in
      127.*|::1) continue ;;
    esac
    if [ -z "$DNS_LIST" ]; then
      DNS_LIST="\"$ns\""
    else
      DNS_LIST="$DNS_LIST, \"$ns\""
    fi
  done
fi

{
  printf '{\n'
  printf '  "storage-driver": "overlay2",\n'
  printf '  "userland-proxy": false'
  if [ -n "$DOCKER_REGISTRY_MIRROR" ]; then
    printf ',\n  "registry-mirrors": ["%s"]' "$DOCKER_REGISTRY_MIRROR"
  fi
  if [ -n "$DNS_LIST" ]; then
    printf ',\n  "dns": [%s]' "$DNS_LIST"
  fi
  printf '\n}\n'
} > /etc/docker/daemon.json

[ -n "$DOCKER_REGISTRY_MIRROR" ] && echo "daemon.json: registry-mirrors -> ${DOCKER_REGISTRY_MIRROR}" >&2
[ -n "$DNS_LIST" ] && echo "daemon.json: dns -> [${DNS_LIST}]" >&2

# /etc/hosts redirect for ghcr.io mirror.
GHCR_HOSTS_MARKER="# proxvex: ghcr mirror"
if [ -n "$GHCR_REGISTRY_MIRROR" ] && ! grep -q "$GHCR_HOSTS_MARKER" /etc/hosts 2>/dev/null; then
  ghcr_mirror_host=$(echo "$GHCR_REGISTRY_MIRROR" | sed -E 's|^https?://||;s|/.*||;s|:.*||')
  ghcr_mirror_ip=$(getent hosts "$ghcr_mirror_host" 2>/dev/null | awk '{print $1; exit}')
  if [ -n "$ghcr_mirror_ip" ]; then
    echo "${ghcr_mirror_ip} ghcr.io  ${GHCR_HOSTS_MARKER}" >> /etc/hosts
    echo "/etc/hosts: ghcr.io -> ${ghcr_mirror_ip} (${ghcr_mirror_host})" >&2
  else
    echo "WARN: ghcr_registry_mirror=${GHCR_REGISTRY_MIRROR} but ${ghcr_mirror_host} is not resolvable — skipping /etc/hosts redirect" >&2
  fi
fi

# nohup + setsid so dockerd survives the SSH/pct exec session that launched it.
nohup setsid /usr/sbin/dockerd \
  >> "$LOG_FILE" 2>&1 < /dev/null &

echo "dockerd started (logs at ${LOG_FILE})" >&2
DOCKEREOF

chmod 755 "$SCRIPT_PATH"
chown "$VOL_OWNER" "$SCRIPT_PATH" 2>/dev/null || true
log "Wrote dockerd on-start script: ${SCRIPT_PATH}"

printf '[{"id":"dockerd_on_start_written","value":"true"}]\n'
