#!/bin/sh
# Write a docker-compose on-stop drop-in script for docker-compose applications.
#
# Docker containers need to stop their listeners and shut down before the LXC
# container itself stops. Without this, processes hang and dockerd is killed
# uncleanly by the kernel. The pre-stop hookscript calls /etc/proxvex/on_stop_container
# synchronously via pct exec, which runs all scripts in /etc/proxvex/on_stop.d/.
#
# Runs on the PVE host (execute_on: ve). The generated scripts are invoked inside
# the container by the hookscript on pre-stop.
#
# Inputs (template variables):
#   hostname - Container hostname
#   vm_id    - Container VMID
#
# Output: JSON to stdout

set -eu

HOSTNAME="{{ hostname }}"
VM_ID="{{ vm_id }}"

log() { echo "$@" >&2; }

# For reconfigure: volumes keep the previous container's hostname, but
# {{ hostname }} carries the scenario's intended new hostname. Look up the
# actual container hostname via pct config so the volume lookup matches.
ACTUAL_HOST=""
if [ -n "$VM_ID" ] && [ "$VM_ID" != "NOT_DEFINED" ]; then
  ACTUAL_HOST=$(pct config "$VM_ID" 2>/dev/null | awk '/^hostname:/ {print $2; exit}' || true)
fi
[ -z "$ACTUAL_HOST" ] && ACTUAL_HOST="$HOSTNAME"

SAFE_HOST=$(pve_sanitize_name "$ACTUAL_HOST")
# Tolerant lookup — see conf-write-dockerd-on-start.sh: a missing proxvex
# volume is a skip, not an installation failure.
VOLUME_DIR=$(resolve_host_volume "$SAFE_HOST" "proxvex" "$VM_ID" 2>/dev/null || echo "")

if [ -z "$VOLUME_DIR" ] || [ ! -d "$VOLUME_DIR" ]; then
  log "Warning: no proxvex volume for ${SAFE_HOST} (vmid ${VM_ID}), skipping"
  printf '[{"id":"dockerd_on_stop_written","value":"false"}]\n'
  exit 0
fi

VOL_OWNER=$(stat -c '%u:%g' "$VOLUME_DIR" 2>/dev/null || echo "0:0")

mkdir -p "${VOLUME_DIR}/on_stop.d"
chown "$VOL_OWNER" "${VOLUME_DIR}/on_stop.d" 2>/dev/null || true

# --- 1. Write on_stop_container dispatcher (only if not already present) ---
DISPATCHER="${VOLUME_DIR}/on_stop_container"
if [ ! -f "$DISPATCHER" ]; then
  cat > "$DISPATCHER" << 'DISPEOF'
#!/bin/sh
# on_stop_container - runs all drop-in scripts on container pre-stop
# Called by Proxmox hookscript via: pct exec <CTID> -- /etc/proxvex/on_stop_container

DROPIN_DIR="/etc/proxvex/on_stop.d"

for script in "$DROPIN_DIR"/*.sh; do
  [ -x "$script" ] || continue
  echo "Running: $script" >&2
  "$script" 2>&1 | while IFS= read -r line; do echo "  $line" >&2; done
done
DISPEOF
  chmod 755 "$DISPATCHER"
  chown "$VOL_OWNER" "$DISPATCHER" 2>/dev/null || true
  log "Wrote dispatcher: $DISPATCHER"
fi

# --- 2. Write docker-compose stop script ---
STOP_SCRIPT="${VOLUME_DIR}/on_stop.d/50-stop-docker-compose.sh"

cat > "$STOP_SCRIPT" << 'STOPEOF'
#!/bin/sh
# Stop Docker Compose containers and dockerd on container pre-stop.
# Generated by proxvex (host-side pre_start).
# Runs synchronously from the Proxmox pre-stop hook via on_stop_container.
#
# Idempotent: exits immediately if dockerd is not running.

LOG_FILE="/var/log/dockerd-stop.log"

echo "=== $(date -u +%FT%TZ) on_stop: stopping docker-compose containers ===" | tee -a "$LOG_FILE" >&2

if ! docker info >/dev/null 2>&1; then
  echo "dockerd not responsive — nothing to stop" | tee -a "$LOG_FILE" >&2
  exit 0
fi

# Stop all running containers with a 10s grace period each.
CONTAINERS=$(docker ps -q 2>/dev/null || true)
if [ -n "$CONTAINERS" ]; then
  echo "Stopping containers: $CONTAINERS" | tee -a "$LOG_FILE" >&2
  docker stop --time 10 $CONTAINERS 2>&1 | tee -a "$LOG_FILE" >&2 || true
else
  echo "No running containers to stop" | tee -a "$LOG_FILE" >&2
fi

# Stop dockerd itself.
DOCKERD_PID="$(cat /var/run/docker.pid 2>/dev/null || pidof dockerd 2>/dev/null || true)"
if [ -n "$DOCKERD_PID" ]; then
  echo "Stopping dockerd (pid: $DOCKERD_PID)" | tee -a "$LOG_FILE" >&2
  kill -TERM "$DOCKERD_PID" 2>&1 | tee -a "$LOG_FILE" >&2 || true

  # Wait up to 10s for dockerd to exit.
  _tries=0
  while [ "$_tries" -lt 5 ]; do
    if ! kill -0 "$DOCKERD_PID" 2>/dev/null; then
      echo "dockerd exited cleanly" | tee -a "$LOG_FILE" >&2
      break
    fi
    sleep 2
    _tries=$((_tries + 1))
  done
  if kill -0 "$DOCKERD_PID" 2>/dev/null; then
    echo "dockerd did not exit within 10s — kernel will force-stop it" | tee -a "$LOG_FILE" >&2
  fi
else
  echo "dockerd pid not found" | tee -a "$LOG_FILE" >&2
fi

echo "=== $(date -u +%FT%TZ) on_stop: done ===" | tee -a "$LOG_FILE" >&2
exit 0
STOPEOF

chmod 755 "$STOP_SCRIPT"
chown "$VOL_OWNER" "$STOP_SCRIPT" 2>/dev/null || true
log "Wrote docker-compose stop script: $STOP_SCRIPT"

printf '[{"id":"dockerd_on_stop_written","value":"true"}]\n'
