#!/bin/sh
# Write on_start_container dispatcher and drop-in scripts to the host-side
# volume directory. When the container starts, these files are available
# at /etc/lxc-oci-deployer/ via bind mount.
#
# This script runs on the PVE host (execute_on: ve) and replaces the
# post_start templates 332, 340, 342, and 325.
#
# Requires:
#   - shared_volpath: Host-side base path for volumes
#   - hostname: Container hostname
#
# Optional:
#   - ssl_mode: proxy/native/certs
#   - CF_TOKEN (from cloudflare stack), acme_san, acme_email, acme.cert_dir
#   - acme.needs_server_cert, acme.needs_ca_cert
#   - http_port, https_port
#   - alpine_mirror, debian_mirror
#   - compose_project
#   - uid, gid
#
# Output: JSON to stdout

set -eu

HOSTNAME="{{ hostname }}"
SSL_MODE="{{ ssl_mode }}"
HTTP_PORT="{{ http_port }}"
HTTPS_PORT="{{ https_port }}"
CF_API_TOKEN="{{ CF_TOKEN }}"
ACME_SAN="{{ acme_san }}"
ACME_EMAIL="{{ acme_email }}"
CERT_DIR="{{ acme.cert_dir }}"
NEEDS_SERVER_CERT="{{ acme_needs_server_cert }}"
NEEDS_CA_CERT="{{ acme_needs_ca_cert }}"
ALPINE_MIRROR="{{ alpine_mirror }}"
DEBIAN_MIRROR="{{ debian_mirror }}"
COMPOSE_PROJECT="{{ compose_project }}"
UID_VALUE="{{ uid }}"
GID_VALUE="{{ gid }}"
ACME_STAGING="{{ acme_staging }}"
SMB_USER="{{ smb_user }}"
SMB_PASSWORD="{{ smb_password }}"

log() { echo "$@" >&2; }

sanitize_name() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

is_set() {
  [ -n "$1" ] && [ "$1" != "NOT_DEFINED" ] && [ "$1" != "" ]
}

SAFE_HOST=$(sanitize_name "$HOSTNAME")
VOLUME_DIR=$(resolve_host_volume "$SAFE_HOST" "oci-deployer")

if [ ! -d "$VOLUME_DIR" ]; then
  log "Warning: Volume directory $VOLUME_DIR does not exist, skipping"
  exit 0
fi

SCRIPTS_WRITTEN=0

# Lock helper snippet — inlined into generated on_start.d scripts to prevent
# concurrent apk/apt from racing with post_start scripts (same lock file).
PKG_LOCK_SNIPPET='
_PKG_LOCK="/tmp/.pkg-common.lock"
_pkg_lock() {
  _tries=0
  while [ "$_tries" -lt 60 ]; do
    if (set -C; echo $$ > "$_PKG_LOCK") 2>/dev/null; then return 0; fi
    _h=$(cat "$_PKG_LOCK" 2>/dev/null || true)
    if [ -n "$_h" ] && ! kill -0 "$_h" 2>/dev/null; then rm -f "$_PKG_LOCK"; continue; fi
    sleep 2; _tries=$((_tries + 1))
  done
  echo "Warning: pkg lock timeout, proceeding" >&2
}
_pkg_unlock() { _h=$(cat "$_PKG_LOCK" 2>/dev/null || true); [ "$_h" = "$$" ] && rm -f "$_PKG_LOCK"; }
'

# Determine ownership from parent volume directory (set by template 150)
VOL_OWNER=$(stat -c '%u:%g' "$VOLUME_DIR" 2>/dev/null || echo "0:0")

# --- 1. Write on_start_container dispatcher ---
mkdir -p "${VOLUME_DIR}/on_start.d"
chown "$VOL_OWNER" "${VOLUME_DIR}/on_start.d" 2>/dev/null || true

cat > "${VOLUME_DIR}/on_start_container" << 'DISPEOF'
#!/bin/sh
# on_start_container - runs all drop-in scripts on container start
# Called by Proxmox hookscript via: pct exec <CTID> -- /etc/lxc-oci-deployer/on_start_container [UID] [GID]

APP_UID="${1:-0}"
APP_GID="${2:-0}"
DROPIN_DIR="/etc/lxc-oci-deployer/on_start.d"

echo "===OCI_HOOK_START===" >&2
HOOK_FAILED=0

for script in "$DROPIN_DIR"/*.sh; do
  [ -x "$script" ] || continue
  echo "Running: $script" >&2
  "$script" "$APP_UID" "$APP_GID"
  RC=$?
  if [ $RC -ne 0 ]; then
    echo "  Script $script failed with exit code $RC" >&2
    HOOK_FAILED=1
  fi
done

if [ "$HOOK_FAILED" -eq 0 ]; then
  echo "===OCI_HOOK_SUCCESS===" >&2
else
  echo "===OCI_HOOK_ERROR===" >&2
fi
DISPEOF
chmod 755 "${VOLUME_DIR}/on_start_container"
chown "$VOL_OWNER" "${VOLUME_DIR}/on_start_container" 2>/dev/null || true
log "Wrote dispatcher: ${VOLUME_DIR}/on_start_container"
SCRIPTS_WRITTEN=$((SCRIPTS_WRITTEN + 1))

# --- 2. Write acme-renew.sh (if addon-acme is enabled) ---
# CERT_DIR is set only by addon-acme (property acme.cert_dir), so its presence
# signals that addon-acme is active. If active, acme_san and CF_API_TOKEN are
# required — abort loudly instead of silently skipping.
if is_set "$CERT_DIR"; then
  if ! is_set "$ACME_SAN"; then
    log "ERROR: addon-acme is enabled (acme.cert_dir='$CERT_DIR') but 'acme_san' is not set."
    log "       Add an 'acme_san' parameter (e.g. '*.example.com,example.com') to the application."
    exit 1
  fi
  if ! is_set "$CF_API_TOKEN"; then
    log "ERROR: addon-acme is enabled but CF_API_TOKEN is not available."
    log "       Ensure a 'cloudflare' stack with CF_TOKEN is linked to the application."
    exit 1
  fi
  ACME_SCRIPT="${VOLUME_DIR}/on_start.d/acme-renew.sh"

  # Part 1: Header with baked-in values
  cat > "$ACME_SCRIPT" <<EOF
#!/bin/sh
# ACME certificate renewal - issue, renew, and maintain
# Generated by oci-lxc-deployer (host-side pre_start)
# Runs on every container start via the on_start_container dispatcher.

CF_API_TOKEN="$CF_API_TOKEN"
ACME_SAN="$ACME_SAN"
ACME_EMAIL="$ACME_EMAIL"
ACME_STAGING="$ACME_STAGING"
CERT_DIR="$CERT_DIR"
NEEDS_SERVER_CERT="$NEEDS_SERVER_CERT"
NEEDS_CA_CERT="$NEEDS_CA_CERT"
ALPINE_MIRROR="$ALPINE_MIRROR"
DEBIAN_MIRROR="$DEBIAN_MIRROR"
EOF

  # Insert package lock helper
  echo "$PKG_LOCK_SNIPPET" >> "$ACME_SCRIPT"

  # Part 2: Script body (no variable expansion)
  cat >> "$ACME_SCRIPT" << 'ACMEEOF'

APP_UID="${1:-0}"
APP_GID="${2:-0}"
export HOME="/root"
ACME_HOME="/root/.acme.sh"
RELOAD_SCRIPT="/etc/lxc-oci-deployer/reload_certificates"

# --- Check if renewal loop already running ---
if pgrep -f "acme-renew-loop" >/dev/null 2>&1; then
  echo "ACME renewal loop already running" >&2
  exit 0
fi

# --- Parse SAN: extract primary domain and build -d flags ---
PRIMARY_DOMAIN=$(echo "$ACME_SAN" | cut -d',' -f1)
ACME_ISSUE_ARGS="--dns dns_cf"
IFS=','
for d in $ACME_SAN; do
  d=$(echo "$d" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  [ -n "$d" ] && ACME_ISSUE_ARGS="$ACME_ISSUE_ARGS -d $d"
done
unset IFS

# --- Use staging server if requested ---
if [ "$ACME_STAGING" = "true" ]; then
  ACME_ISSUE_ARGS="$ACME_ISSUE_ARGS --server letsencrypt_test"
  echo "Using Let's Encrypt STAGING server (no rate limits)" >&2
fi

# --- Detect OS ---
OS_TYPE=""
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_TYPE="$ID"
elif command -v apk >/dev/null 2>&1; then
  OS_TYPE="alpine"
elif command -v apt-get >/dev/null 2>&1; then
  OS_TYPE="debian"
fi

# --- Install curl and openssl if not present (with network retry) ---
if ! command -v curl >/dev/null 2>&1 || ! command -v openssl >/dev/null 2>&1; then
  echo "Installing curl and openssl..." >&2
  _pkg_lock
  case "$OS_TYPE" in
    alpine)
      if [ -n "$ALPINE_MIRROR" ]; then
        ALPINE_VERSION=$(cut -d. -f1,2 < /etc/alpine-release 2>/dev/null)
        if [ -n "$ALPINE_VERSION" ]; then
          cat > /etc/apk/repositories <<MIRROREOF
${ALPINE_MIRROR}/v${ALPINE_VERSION}/main
${ALPINE_MIRROR}/v${ALPINE_VERSION}/community
MIRROREOF
          echo "Set Alpine mirror: $ALPINE_MIRROR" >&2
        fi
      fi
      apk update >&2
      apk add --no-cache curl openssl >&2
      ;;
    debian|ubuntu)
      if [ -n "$DEBIAN_MIRROR" ]; then
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          CODENAME="$VERSION_CODENAME"
        fi
        if [ -z "$CODENAME" ]; then
          CODENAME="stable"
        fi
        cat > /etc/apt/sources.list <<MIRROREOF
deb ${DEBIAN_MIRROR} ${CODENAME} main
deb ${DEBIAN_MIRROR} ${CODENAME}-updates main
MIRROREOF
        echo "Set Debian mirror: $DEBIAN_MIRROR" >&2
      fi
      export DEBIAN_FRONTEND=noninteractive
      # Retry apt-get update until network is available (up to 2 min)
      PKG_ATTEMPT=0
      while [ $PKG_ATTEMPT -lt 24 ]; do
        if apt-get update -qq >&2 2>&1; then
          break
        fi
        PKG_ATTEMPT=$((PKG_ATTEMPT + 1))
        echo "Waiting for package repository (attempt $PKG_ATTEMPT/24)..." >&2
        sleep 5
      done
      apt-get install -y --no-install-recommends curl openssl >&2
      ;;
  esac
  _pkg_unlock
fi

# --- Install acme.sh if not present ---
if [ ! -f "$ACME_HOME/acme.sh" ]; then
  echo "Installing acme.sh..." >&2
  if [ -n "$ACME_EMAIL" ]; then
    curl -s https://get.acme.sh | sh -s email="$ACME_EMAIL" >&2
  else
    curl -s https://get.acme.sh | sh >&2
  fi
  if [ ! -f "$ACME_HOME/acme.sh" ]; then
    echo "ERROR: Failed to install acme.sh" >&2
    exit 1
  fi
  echo "acme.sh installed successfully" >&2
fi

# --- Function: issue or renew certificate ---
acme_issue_or_renew() {
  export CF_Token="$CF_API_TOKEN"

  # Build install command args based on needs_server_cert / needs_ca_cert
  INSTALL_ARGS=""
  if [ "$NEEDS_SERVER_CERT" = "true" ]; then
    INSTALL_ARGS="$INSTALL_ARGS --key-file ${CERT_DIR}/privkey.pem"
    INSTALL_ARGS="$INSTALL_ARGS --cert-file ${CERT_DIR}/cert.pem"
    INSTALL_ARGS="$INSTALL_ARGS --fullchain-file ${CERT_DIR}/fullchain.pem"
  fi
  if [ "$NEEDS_CA_CERT" = "true" ]; then
    INSTALL_ARGS="$INSTALL_ARGS --ca-file ${CERT_DIR}/chain.pem"
  fi

  if [ -z "$INSTALL_ARGS" ]; then
    echo "WARNING: Neither server cert nor CA cert requested, nothing to do" >&2
    return 0
  fi

  # Issue certificate if not yet issued for primary domain
  if ! "$ACME_HOME/acme.sh" --list | grep -q "$PRIMARY_DOMAIN"; then
    echo "Issuing certificate for SAN: $ACME_SAN..." >&2
    "$ACME_HOME/acme.sh" --issue $ACME_ISSUE_ARGS >&2
    ISSUE_RC=$?
    if [ $ISSUE_RC -ne 0 ] && [ $ISSUE_RC -ne 2 ]; then
      echo "ERROR: Failed to issue certificate (exit code: $ISSUE_RC)" >&2
      return 1
    fi
  else
    echo "Certificate for $PRIMARY_DOMAIN already issued, attempting renewal..." >&2
    "$ACME_HOME/acme.sh" --renew -d "$PRIMARY_DOMAIN" >&2 || true
  fi

  # Install certificate files to target directory
  mkdir -p "$CERT_DIR"
  echo "Installing certificate files to $CERT_DIR..." >&2
  "$ACME_HOME/acme.sh" --install-cert -d "$PRIMARY_DOMAIN" $INSTALL_ARGS >&2
  if [ $? -ne 0 ]; then
    echo "ERROR: Failed to install certificate files" >&2
    return 1
  fi

  # Set ownership
  if [ "$APP_UID" != "0" ] || [ "$APP_GID" != "0" ]; then
    chown -R "${APP_UID}:${APP_GID}" "$CERT_DIR" 2>/dev/null || true
  fi

  echo "Certificate files installed successfully" >&2
  return 0
}

# --- Initial certificate issuance (synchronous) ---
acme_issue_or_renew

# --- Start background renewal loop ---
(
  # Tag the process for pgrep detection
  exec -a acme-renew-loop sh -c '
    while true; do
      sleep 86400
      echo "[acme-renew-loop] Checking certificate renewal..." >&2
      "'"$ACME_HOME"'/acme.sh" --renew -d "'"$PRIMARY_DOMAIN"'" >&2 || true

      # Reinstall cert files
      INSTALL_ARGS=""
      if [ "'"$NEEDS_SERVER_CERT"'" = "true" ]; then
        INSTALL_ARGS="$INSTALL_ARGS --key-file '"${CERT_DIR}"'/privkey.pem"
        INSTALL_ARGS="$INSTALL_ARGS --cert-file '"${CERT_DIR}"'/cert.pem"
        INSTALL_ARGS="$INSTALL_ARGS --fullchain-file '"${CERT_DIR}"'/fullchain.pem"
      fi
      if [ "'"$NEEDS_CA_CERT"'" = "true" ]; then
        INSTALL_ARGS="$INSTALL_ARGS --ca-file '"${CERT_DIR}"'/chain.pem"
      fi
      if [ -n "$INSTALL_ARGS" ]; then
        "'"$ACME_HOME"'/acme.sh" --install-cert -d "'"$PRIMARY_DOMAIN"'" $INSTALL_ARGS >&2 || true
      fi

      # Set ownership
      if [ "'"$APP_UID"'" != "0" ] || [ "'"$APP_GID"'" != "0" ]; then
        chown -R "'"${APP_UID}:${APP_GID}"'" "'"$CERT_DIR"'" 2>/dev/null || true
      fi

      # Trigger reload hook if present
      if [ -x "'"$RELOAD_SCRIPT"'" ]; then
        echo "[acme-renew-loop] Running reload_certificates hook..." >&2
        "'"$RELOAD_SCRIPT"'" >&2 || true
      fi
    done
  '
) &

echo "ACME renewal loop started in background (PID: $!)" >&2
ACMEEOF

  chmod 755 "$ACME_SCRIPT"
  chown "$VOL_OWNER" "$ACME_SCRIPT" 2>/dev/null || true
  log "Wrote ACME renewal script: ${ACME_SCRIPT}"
  SCRIPTS_WRITTEN=$((SCRIPTS_WRITTEN + 1))
fi

# --- 3. Write ssl-proxy.sh (if proxy mode) ---
if [ "$SSL_MODE" = "proxy" ]; then
  SSL_SCRIPT="${VOLUME_DIR}/on_start.d/ssl-proxy.sh"

  # Part 1: Header with baked-in values
  cat > "$SSL_SCRIPT" <<EOF
#!/bin/sh
# SSL proxy on-start script - nginx reverse proxy with TLS termination
# Generated by oci-lxc-deployer (host-side pre_start)
# Runs on every container start via the on_start_container dispatcher.

SSL_MODE="$SSL_MODE"
HTTP_PORT="$HTTP_PORT"
HTTPS_PORT="$HTTPS_PORT"
ALPINE_MIRROR="$ALPINE_MIRROR"
DEBIAN_MIRROR="$DEBIAN_MIRROR"
COMPOSE_PROJECT="$COMPOSE_PROJECT"
EOF

  # Insert package lock helper
  echo "$PKG_LOCK_SNIPPET" >> "$SSL_SCRIPT"

  # Part 2: Script body (no variable expansion)
  cat >> "$SSL_SCRIPT" << 'SSLEOF'

APP_UID="${1:-0}"
APP_GID="${2:-0}"
CERT_DIR="/etc/ssl/addon"
NGINX_CONF_DIR=""

# --- Docker-Compose detection ---
# If this is a compose app with SSL overlay, copy and start
OCI_COMPOSE_DIR="/etc/lxc-oci-deployer/docker-compose/${COMPOSE_PROJECT}"
if [ -n "$COMPOSE_PROJECT" ] && [ "$COMPOSE_PROJECT" != "NOT_DEFINED" ] && [ -d "$OCI_COMPOSE_DIR" ]; then
  TARGET_DIR="/opt/docker-compose/${COMPOSE_PROJECT}"
  if [ -d "$TARGET_DIR" ]; then
    echo "Copying SSL-injected compose overlay to $TARGET_DIR..." >&2
    cp -f "$OCI_COMPOSE_DIR"/* "$TARGET_DIR/" 2>/dev/null || true
    cd "$TARGET_DIR" || exit 0
    docker compose up -d >&2 2>&1 || true
    exit 0
  fi
fi

# --- Check for existing compose app without SSL overlay ---
if [ -d /opt/docker-compose ]; then
  COMPOSE_DIR=$(find /opt/docker-compose -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)
  if [ -n "$COMPOSE_DIR" ]; then
    echo "Docker-Compose app detected, ensuring services are running..." >&2
    cd "$COMPOSE_DIR" || exit 0
    docker compose up -d >&2 2>&1 || true
    exit 0
  fi
fi

# --- Check if certificates exist ---
if [ ! -f "${CERT_DIR}/fullchain.pem" ] || [ ! -f "${CERT_DIR}/privkey.pem" ]; then
  echo "Warning: SSL certificates not found in ${CERT_DIR}, skipping proxy setup" >&2
  exit 0
fi

# --- Check if nginx is already running ---
if pgrep -x nginx >/dev/null 2>&1; then
  echo "nginx already running" >&2
  exit 0
fi

# --- Detect OS ---
OS_TYPE=""
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_TYPE="$ID"
elif command -v apk >/dev/null 2>&1; then
  OS_TYPE="alpine"
elif command -v apt-get >/dev/null 2>&1; then
  OS_TYPE="debian"
fi

# --- Install nginx and iptables if not present ---
if ! command -v nginx >/dev/null 2>&1 || ! command -v iptables >/dev/null 2>&1; then
  echo "Installing nginx and iptables..." >&2
  _pkg_lock

  case "$OS_TYPE" in
    alpine)
      if [ -n "$ALPINE_MIRROR" ]; then
        ALPINE_VERSION=$(cut -d. -f1,2 < /etc/alpine-release 2>/dev/null)
        if [ -n "$ALPINE_VERSION" ]; then
          cat > /etc/apk/repositories <<MIRROREOF
${ALPINE_MIRROR}/v${ALPINE_VERSION}/main
${ALPINE_MIRROR}/v${ALPINE_VERSION}/community
MIRROREOF
          echo "Set Alpine mirror: $ALPINE_MIRROR" >&2
        fi
      fi
      apk update >&2
      apk add --no-cache nginx iptables >&2
      ;;
    debian|ubuntu)
      if [ -n "$DEBIAN_MIRROR" ]; then
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          CODENAME="$VERSION_CODENAME"
        fi
        if [ -z "$CODENAME" ]; then
          CODENAME="stable"
        fi
        cat > /etc/apt/sources.list <<MIRROREOF
deb ${DEBIAN_MIRROR} ${CODENAME} main
deb ${DEBIAN_MIRROR} ${CODENAME}-updates main
MIRROREOF
        echo "Set Debian mirror: $DEBIAN_MIRROR" >&2
      fi
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -qq >&2
      apt-get install -y --no-install-recommends nginx iptables >&2
      ;;
  esac
  _pkg_unlock
fi

# --- Determine nginx config directory ---
if [ -d /etc/nginx/http.d ]; then
  NGINX_CONF_DIR="/etc/nginx/http.d"
  rm -f /etc/nginx/http.d/default.conf 2>/dev/null
elif [ -d /etc/nginx/sites-enabled ]; then
  NGINX_CONF_DIR="/etc/nginx/conf.d"
  rm -f /etc/nginx/sites-enabled/default 2>/dev/null
  mkdir -p /etc/nginx/conf.d
elif [ -d /etc/nginx/conf.d ]; then
  NGINX_CONF_DIR="/etc/nginx/conf.d"
else
  NGINX_CONF_DIR="/etc/nginx/conf.d"
  mkdir -p "$NGINX_CONF_DIR"
fi

# --- Write nginx SSL config ---
cat > "${NGINX_CONF_DIR}/ssl-proxy.conf" <<NGINXEOF
server {
    listen ${HTTPS_PORT} ssl;
    server_name _;

    ssl_certificate ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:${HTTP_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 86400;
    }
}
NGINXEOF

echo "Wrote nginx SSL config to ${NGINX_CONF_DIR}/ssl-proxy.conf" >&2

# --- Set iptables rules to block external HTTP access ---
iptables -C INPUT -i lo -p tcp --dport "${HTTP_PORT}" -j ACCEPT 2>/dev/null || \
  iptables -I INPUT -i lo -p tcp --dport "${HTTP_PORT}" -j ACCEPT

iptables -C INPUT -p tcp --dport "${HTTP_PORT}" -j DROP 2>/dev/null || \
  iptables -A INPUT -p tcp --dport "${HTTP_PORT}" -j DROP

echo "iptables: blocked external access to HTTP port ${HTTP_PORT}" >&2

# --- Ensure nginx dirs are writable by app user ---
if [ "$APP_UID" != "0" ]; then
  for dir in /var/lib/nginx /var/log/nginx /run/nginx; do
    mkdir -p "$dir" 2>/dev/null
    chown -R "${APP_UID}:${APP_GID}" "$dir" 2>/dev/null || true
  done
fi

# --- Start nginx as the application user ---
echo "Starting nginx as UID ${APP_UID}..." >&2
if [ "$APP_UID" != "0" ]; then
  su -s /bin/sh -c "nginx" "$(getent passwd "$APP_UID" | cut -d: -f1 2>/dev/null || echo "#${APP_UID}")" >&2 || \
    nginx -g "user #${APP_UID} #${APP_GID};" >&2
else
  nginx >&2
fi

# --- Create reload_certificates hook for ACME renewal ---
RELOAD_SCRIPT="/etc/lxc-oci-deployer/reload_certificates"
cat > "$RELOAD_SCRIPT" <<'RELOADEOF'
#!/bin/sh
# Reload nginx to pick up renewed certificates
nginx -s reload >&2
RELOADEOF
chmod 755 "$RELOAD_SCRIPT"
echo "Created certificate reload hook: $RELOAD_SCRIPT" >&2

echo "SSL proxy setup complete (HTTPS on port ${HTTPS_PORT})" >&2
SSLEOF

  chmod 755 "$SSL_SCRIPT"
  chown "$VOL_OWNER" "$SSL_SCRIPT" 2>/dev/null || true
  log "Wrote SSL proxy script: ${SSL_SCRIPT}"
  SCRIPTS_WRITTEN=$((SCRIPTS_WRITTEN + 1))
fi

# --- 4. Write docker-compose SSL injection (if compose app + proxy mode) ---
if [ "$SSL_MODE" = "proxy" ] && is_set "$COMPOSE_PROJECT" && is_set "$HTTP_PORT" && is_set "$HTTPS_PORT"; then
  COMPOSE_DIR="${VOLUME_DIR}/docker-compose/${COMPOSE_PROJECT}"
  mkdir -p "$COMPOSE_DIR"

  # Write nginx SSL config for compose
  cat > "${COMPOSE_DIR}/nginx-ssl.conf" <<NGINXEOF
server {
    listen ${HTTPS_PORT} ssl;
    server_name _;

    ssl_certificate /etc/ssl/addon/fullchain.pem;
    ssl_certificate_key /etc/ssl/addon/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://upstream:${HTTP_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}
NGINXEOF

  chown -R "$VOL_OWNER" "$COMPOSE_DIR" 2>/dev/null || true
  log "Wrote compose nginx config: ${COMPOSE_DIR}/nginx-ssl.conf"
  SCRIPTS_WRITTEN=$((SCRIPTS_WRITTEN + 1))
fi

# --- 5. Write smbd.sh (if Samba addon configured) ---
if is_set "$SMB_USER"; then
  SMB_SCRIPT="${VOLUME_DIR}/on_start.d/smbd.sh"

  # Part 1: Header with baked-in values
  cat > "$SMB_SCRIPT" <<EOF
#!/bin/sh
# Samba service - install, configure and start
# Generated by oci-lxc-deployer (host-side pre_start)
# Runs on every container start via the on_start_container dispatcher.

SMB_USER="$SMB_USER"
SMB_PASSWORD="$SMB_PASSWORD"
ALPINE_MIRROR="$ALPINE_MIRROR"
DEBIAN_MIRROR="$DEBIAN_MIRROR"
EOF

  # Insert package lock helper
  echo "$PKG_LOCK_SNIPPET" >> "$SMB_SCRIPT"

  # Part 2: Script body (no variable expansion)
  cat >> "$SMB_SCRIPT" << 'SMBEOF'

# --- If smbd is already running, nothing to do ---
if pgrep -x smbd >/dev/null 2>&1; then
  echo "smbd already running" >&2
  exit 0
fi

# --- Detect OS ---
OS_TYPE=""
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_TYPE="$ID"
elif command -v apk >/dev/null 2>&1; then
  OS_TYPE="alpine"
elif command -v apt-get >/dev/null 2>&1; then
  OS_TYPE="debian"
fi

# --- Install samba if not present ---
if ! command -v smbd >/dev/null 2>&1; then
  echo "Installing samba..." >&2
  _pkg_lock

  case "$OS_TYPE" in
    alpine)
      if [ -n "$ALPINE_MIRROR" ]; then
        ALPINE_VERSION=$(cut -d. -f1,2 < /etc/alpine-release 2>/dev/null)
        if [ -n "$ALPINE_VERSION" ]; then
          cat > /etc/apk/repositories <<MIRROREOF
${ALPINE_MIRROR}/v${ALPINE_VERSION}/main
${ALPINE_MIRROR}/v${ALPINE_VERSION}/community
MIRROREOF
          echo "Set Alpine mirror: $ALPINE_MIRROR" >&2
        fi
      fi
      apk update >&2
      apk add --no-cache samba >&2
      ;;
    debian|ubuntu)
      if [ -n "$DEBIAN_MIRROR" ]; then
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          CODENAME="$VERSION_CODENAME"
        fi
        if [ -z "$CODENAME" ]; then
          CODENAME="stable"
        fi
        cat > /etc/apt/sources.list <<MIRROREOF
deb ${DEBIAN_MIRROR} ${CODENAME} main
deb ${DEBIAN_MIRROR} ${CODENAME}-updates main
MIRROREOF
        echo "Set Debian mirror: $DEBIAN_MIRROR" >&2
      fi
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -qq >&2
      apt-get install -y --no-install-recommends samba >&2
      ;;
  esac
  _pkg_unlock
fi

# --- Create directories ---
mkdir -p /etc/samba
mkdir -p /var/lib/samba/private

# --- Create user if not exists ---
if [ -n "$SMB_USER" ] && ! id "$SMB_USER" >/dev/null 2>&1; then
  echo "Creating user '$SMB_USER'..." >&2
  if command -v adduser >/dev/null 2>&1; then
    adduser -D -H -s /sbin/nologin "$SMB_USER" >&2
  elif command -v useradd >/dev/null 2>&1; then
    useradd -r -M -s /usr/sbin/nologin "$SMB_USER" >&2
  fi
fi

# --- Set samba password if user has no samba entry ---
if [ -n "$SMB_USER" ] && [ -n "$SMB_PASSWORD" ]; then
  if ! pdbedit -L 2>/dev/null | grep -q "^${SMB_USER}:"; then
    echo "Setting Samba password for '$SMB_USER'..." >&2
    printf '%s\n%s\n' "$SMB_PASSWORD" "$SMB_PASSWORD" | smbpasswd -a -s "$SMB_USER" >&2
    smbpasswd -e "$SMB_USER" >&2
  fi
fi

# --- Start daemons ---
echo "Starting smbd..." >&2
smbd -D >&2
echo "Starting nmbd..." >&2
nmbd -D >&2
SMBEOF

  chmod 755 "$SMB_SCRIPT"
  chown "$VOL_OWNER" "$SMB_SCRIPT" 2>/dev/null || true
  log "Wrote Samba on-start script: ${SMB_SCRIPT}"
  SCRIPTS_WRITTEN=$((SCRIPTS_WRITTEN + 1))
fi

log "on_start scripts written: ${SCRIPTS_WRITTEN} files to ${VOLUME_DIR}"

printf '[{"id":"on_start_scripts_written","value":"%s"}]\n' "$SCRIPTS_WRITTEN"
