#!/bin/sh
# Upload file: Mosquitto Configuration
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_mosquitto_configuration_content }}" \
  "{{ upload_mosquitto_configuration_destination }}" \
  "Mosquitto Configuration" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_mosquitto_configuration_uploaded"
